# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:nightly

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Flake8
        run: flake8 .

      # Runs a single command using the runners shell
      - name: Run unit tests in serial
        run: pytest .

      - name: Run unit tests in parallel
        run: mpirun -np 2 python3 -m pytest .

      # Runs a set of commands using the runners shell
      - name: Run demo in serial
        run: python3 thermomech.py

      - name: Run demo in parallel
        run:  mpirun -n 2 python3 thermomech.py
